### ISSUE TITLE
JitsiMeetingWidget estimated arrival time

### ISSUE THREAD

**Issue by shipon-eye** [kontinuity/jitsi_meet_adv#1]
Thanks a lot for making it advance.
By the way, what is your estimated completion time of JitsiMeetingWidget?
I am eagerly waiting for it.

**Comment by kontinuity** [comment]
I moved to a private fork since the changes were too specific for my business. I am hoping to merge back a lot of changes into this repo soon.

**Comment by shipon-eye** [comment]
Thanks for the answer.
By the way, I need the JitsiMeetingWidget immediately. So, I am trying to make your source workable. But unfortunately, it throws "Enclosing Activity must implement JitsiMeetActivityInterface" error. I can understand that the default MainActivity has no implementation of  JitsiMeetActivityInterface. Should I create an intermediate Activity with this interface? How can I overcome it. Did you manage to overcome it?
Please help me to solve it, so that I can continue my project.
Thanks in advance
